#pragma once

#ifndef TERMCOLOR_DISABLE

#define TERMCOLOR_RESET "\x1b[0m"
#define TERMCOLOR_BLACK "\x1b[30m"
#define TERMCOLOR_RED "\x1b[31m"
#define TERMCOLOR_GREEN "\x1b[32m"
#define TERMCOLOR_YELLOW "\x1b[33m"
#define TERMCOLOR_BLUE "\x1b[34m"
#define TERMCOLOR_MAGENTA "\x1b[35m"
#define TERMCOLOR_CYAN "\x1b[36m"
#define TERMCOLOR_WHITE "\x1b[37m"

#define TERMCOLOR_BRIGHT_BLACK "\x1b[30;1m"
#define TERMCOLOR_BRIGHT_RED "\x1b[31;1m"
#define TERMCOLOR_BRIGHT_GREEN "\x1b[32;1m"
#define TERMCOLOR_BRIGHT_YELLOW "\x1b[33;1m"
#define TERMCOLOR_BRIGHT_BLUE "\x1b[34;1m"
#define TERMCOLOR_BRIGHT_MAGENTA "\x1b[35;1m"
#define TERMCOLOR_BRIGHT_CYAN "\x1b[36;1m"
#define TERMCOLOR_BRIGHT_WHITE "\x1b[37;1m"

#define TERMCOLOR(__COLOR, __TEXT) TERMCOLOR_##__COLOR __TEXT TERMCOLOR_RESET

#else

#define TERMCOLOR(__COLOR, __TEXT) __TEXT

#endif
